---
title: "Thesis (Random)"
author: "Miguel"
date: "April 8, 2015"
output: html_document
---

How random is this trial?

```{r, echo = FALSE}
suppressWarnings(library(ggplot2))
library(tidyr)
library(dplyr)
```

```{r}
set.seed(4)

# Import data.
data <- c("R", "T", "T", "T", "R", "T", "T", "R", "T", "R","R","R","R","T", "R","R","R","R","R","T", "R","R","R","T","R","R","R","R","R","R","R","R","T", "T", "T", "T", "R", "R", "R", "T", "T", "R", "T","T", "R", "T", "T","R","T", "T", "R", "R", "T", "T", "R", "T", "R","R","R","R","T", "T", "T", "R", "T", "T", "R")

# Write function to calculate the streak of transmissions.
calc_streak <- function(x){
    diff(which(c(0, as.numeric(x == "T"), 0) == 0)) - 1
}

# Calculate streak of data.
streak <- calc_streak(data)


# Reproduce with a simulation. Calculate streaks of simulation.
T_prob <- 31.0/length(data)
outcomes <- c("T", "R")
sim_data <- sample(outcomes, size = length(data), replace = TRUE, prob = c(T_prob, (1-T_prob)))
sim <- calc_streak(sim_data)


# Format real and simulated data for plots.
st <- data.frame(streak) %>% 
  group_by(streak) %>% 
  summarize(results = n()) %>%
  rename(actual_streak = streak)

su <- data.frame(sim) %>% 
  group_by(sim) %>% 
  summarize(results = n()) %>%
  rename(sim_streak = sim)

all <- full_join(st,su, by= "results")
all[is.na(all)] <- 0
all.long <- gather(all, "variable","value", -results)


# Plot.
ggplot(all.long, aes(value, results, fill=variable)) + 
  geom_bar(stat="identity", position="dodge") +
  ggtitle("Data vs. Simulation of Tranmission Counts") + ylab("Transmission Streaks")
```


```{r, echo=FALSE}
# Write function to calculate the streak of reflections.
calc_streak <- function(x){
    diff(which(c(0, as.numeric(x == "R"), 0) == 0)) - 1
}

# Calculate streak of data.
streak <- calc_streak(data)


# Calculate streaks of simulation.
sim <- calc_streak(sim_data)


# Format real and simulated data for plots.
st <- data.frame(streak) %>% 
  group_by(streak) %>% 
  summarize(results = n()) %>%
  rename(actual_streak = streak)

su <- data.frame(sim) %>% 
  group_by(sim) %>% 
  summarize(results = n()) %>%
  rename(sim_streak = sim)

all <- full_join(st,su, by= "results")
all[is.na(all)] <- 0
all.long <- gather(all, "variable","value", -results)


# Plot.
ggplot(all.long, aes(value, results, fill=variable)) + 
  geom_bar(stat="identity", position="dodge") +
  ggtitle("Data vs. Simulation of Tranmission Counts") + ylab("Transmission Streaks")
```
Now let's look at some of the data.
```{r}
h <- c(1.52,1.27,1.02,1.51,1.26,1.01,1.26)
h_E <- c(0.04, 0.035, 0.034, 0.034, 0.034,0.034,0.034) 
T <- c(1.0, 2/24, 0.0, 17/17, 7/19, 0/18, 4/13)
barrier <- c(2.75,3.0,3.25,2.75,3.0,3.25,3.0)
trial <- c(1,1,1,2,2,2,3)

D1 <- round(mean(c(0.9876,1.011,1.048,0.9968,0.9789,0.9676,0.9969,0.9969,0.9672)), digits = 2)
D_SE1 <- round(sd(c(0.9876,1.011,1.048,0.9968,0.9789,0.9676,0.9969,0.9969,0.9672))/sqrt(9), digits = 2)

D2 <- round(mean(c(1.042,1.094,1.113,1.011,1.154, 1.030,1.054,1.078)), digits = 2)
D_SE2 <- round(sd(c(1.042,1.094,1.113,1.011,1.154, 1.030,1.054,1.078))/sqrt(9), digits = 2)

D3 <- round(mean(c(1.089,0.9754,1.058,1.001,0.9794,1.030,0.9193,0.9878,1.090)), digits = 2)
D_SE3 <- round(sd(c(1.089,0.9754,1.058,1.001,0.9794,1.030,0.9193,0.9878,1.090))/sqrt(9), digits = 2)

D <- c(D1,D1,D1,D2,D2,D2,D3)
sd(rep(c(1,0), times = c(2,22)))/sqrt(24)
SE <- c(0,sd(rep(c(1,0), times = c(2,22)))/sqrt(24), 0, 0, sd(rep(c(1,0), times = c(7,12)))/sqrt(19),0, sd(rep(c(1,0), times = c(4,9)))/sqrt(13))
length(SE)
df <- data.frame(trial, barrier, h, h_E, T, D, SE)

  
ggplot(df, aes(h, T, col = factor(D), shape = factor(D))) + 
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin=h-h_E, xmax=h+h_E), height=.03) +
  xlab("Oil Height (mm)") + 
  ylab("Probability of Tunneling") +
  geom_errorbar(aes(ymin = T + SE , ymax = T-SE), width = 0.03) +
  #ggtitle("Tunneling Probability by\n Height of Oil Above Barrier") +
  guides(colour = guide_legend("Droplet\nDiameter (mm)"), shape = guide_legend("Droplet\nDiameter (mm)")) 


```

```{r}
trial <- rep(c(1,2,3),times = c(24,54,11))
Dia <- rep(c(D1,D2,D3), times = c(24,54,11))
height <- rep(c(1.27,1.51,1.26,1.01,1.26), times = c(24,17,19,18,11))
bar <- rep(c(2.75,3.0,3.25,2.75,3.0,3.25,3.0), times = c(0,24,0,17,19,18,11))
collision <- c(seq(1,24),seq(1,17),seq(1,19),seq(1,18),seq(1,11))
gamma <- rep(c(264,268,264,252,256), times = c(24,17,19,18,11))
gammaF <- rep(c(270,270,268,256,262), times = c(24,17,19,18,11))
v_perp <- c(1.67,5.90,6.07,6.66,6.21,6.99,8.49,8.53,7.49,7.45,4.10,4.51,6.72,7.24,7.31,7.11,7.72,5.07,5.19,4.30,4.81,5.23,6.22,6.64,9.05,8.60,9.59,9.38,10.33,8.70,9.60,8.69,10.25,9.98,9.72,9.91,9.00,9.99,9.95,10.27,10.38,5.02,5.89,9.20,6.48,8.23,10.40,10.76,9.62,7.21,8.03,9.25,8.44,9.75,10.77,4.95,8.18,10.05,11.67,3.91,9.41,9.59,10.30,8.85,7.43,9.75,6.26,8.61,10.81,9.57,9.55,9.73,10.92,6.70,5.18,9.23,3.82,8.02,7.57,5.78,7.32,9.62,7.95,7.35,4.38,8.58,8.08,6.94,9.86)
tun <- c("R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","T","R","R","R","R","T","R","T","T","T","T","T","T","T","T","T","T","T","T","T","T","T","T","T","R","R","R","T","T","R","T","T","R","T","T","R","R","R","R","R","R","T","R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","R","T","R","T","R","T","R","R","T")
verr <- rep(0.2,times = (24+54+11))
vdf <- data.frame(trial,collision, Dia, bar, height, v_perp, verr, tun, gamma, gammaF)

vdf <- mutate(vdf, "Memory" = gamma/gammaF)



sd(unique(vdf$Memory))

memory_SE <- sd(unique((vdf$gamma)/vdf$gammaF))/sqrt(length(unique((vdf$gamma)/vdf$gammaF)))
memory_AVG <- mean(unique(vdf$Memory))

ggplot(vdf, aes(x = height, v_perp, col = factor(tun))) + 
  geom_point(size = 3, aes(shape = factor(Dia))) +
  xlab("Oil Height (mm)") +
  ylab("Perpendicular Velocity (mm/s)") +
  ggtitle("Is Tunneling Dependent on\nPerpendicular Velocity?") + 
  guides(colour = guide_legend("Tunneling"), shape = guide_legend("Droplet\nDiameter (mm)"))


# FIRST PLOT AGAIN

ggplot(df, aes(height, , col = factor(D), shape = factor(D))) + 
  geom_point(size = 3) +
  geom_errorbarh(aes(xmin=h-h_E, xmax=h+h_E), height=.03) +
  xlab("Oil Height (mm)") + 
  ylab("Probability of Tunneling") +
  #ggtitle("Tunneling Probability by\n Height of Oil Above Barrier") +
  guides(colour = guide_legend("Droplet\nDiameter (mm)"), shape = guide_legend("Droplet\nDiameter (mm)"))



# Assuming about the same height.

#ggplot(vdf, aes(x = Dia, v_perp, col = factor(tun))) + 
#  geom_point(size = 3, aes(shape = factor(tun))) +
#  xlab("Droplet Diameter (mm)") +
#  ylab("Perpendicular Velocity (mm/s)") +
#  ggtitle("Is Tunneling Dependent on\nPerpendicular Velocity?") + 
#  scale_color_discrete("Droplet\nDiameter (mm)") +
#  guides(colour = guide_legend("Tunneling"), shape = guide_legend("Tunneling"))

# Adding jitter

vdf <- mutate(vdf, jitterD = jitter(Dia)) 
vdf <- mutate(vdf, jittert = jitter(trial))

ggplot(vdf, aes(x = jittert, v_perp, col = factor(tun))) + 
  geom_point(size = 3, aes(shape = factor(Dia))) +
  xlab("Trial") +
  ylab("Perpendicular Velocity (mm/s)") +
  #ggtitle("Is Tunneling Dependent on\nPerpendicular Velocity?") +
  guides(colour = guide_legend("Tunneling"), shape = guide_legend("Droplet\nDiameter (mm)")) +
  scale_x_discrete(limits = c(1,2,3),labels=c("1","2","3")) +
  coord_cartesian(xlim = c(0.5,3.5)) +
  geom_errorbar(aes(ymin=v_perp-verr, ymax=v_perp+verr), width=0.03) 

# Rounds to nearest 2
roundcust <- function(x){
  ifelse(0 < x & x <= 2, 1,
         ifelse(2<x& x <=4, 3,
                ifelse(4<x& x <=6, 5,
                       ifelse(6<x& x <=8, 7,
                              ifelse(8<x& x <=10, 9,
                                     ifelse(10<x& x <=12, 11,                                           
                                            ifelse(12<x& x <=14, 13,0)
                                            ))))))}

roundcust(12.1)
vgroup <- subset(vdf, bar == 3.00) %>%
  mutate(tun_binary  = ifelse(tun == "R", 0,1)) %>%
  mutate(vbin = roundcust(v_perp)) %>%
  group_by(trial, Dia, vbin) %>%
  summarize(prob = mean(tun_binary), num = n(), se = sd(tun_binary)/n())

vgroup[is.na(vgroup)] <- 0
  
ggplot(vgroup, aes(vbin, prob, col = factor(Dia))) + 
  geom_point(aes(size = num)) +
  geom_smooth(method="auto") +
  xlab("Velocity (mm/s)") +
  ylab("Probability of Tunneling") +
  guides( size = guide_legend("Number of\nDatapoints"),
          colour = guide_legend("Droplet\nDiameter (mm)")) +
  #geom_errorbarh(aes(xmin=vbin-1.0, xmax=vbin+1.0), height=0.01) +
  geom_errorbar(aes(ymin = prob-se, ymax = prob+se), width = 0.2) +
  scale_size_area(max_size = 5,breaks=c(1,5,10,13))
  
  

#Boxplot
ggplot(vdf, aes(x = Dia, y = v_perp, col = factor(Dia))) + 
  geom_boxplot() +
  xlab("Diameter") +
  ylab("Perpendicular Velocity (mm/s)") +
  ggtitle("Is Tunneling Dependent on\nPerpendicular Velocity?") 
  #guides(colour = guide_legend("Tunneling"), shape = guide_legend("Droplet\nDiameter (mm)")) 
  #scale_x_discrete(limits = c(1,2,3),labels=c("1","2","3")) +
  #coord_cartesian(xlim = c(0.95,1.10)) 

```